// frontend/src/app/components/input-bar/input-bar.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { ChatService } from '../../services/chat.service';
import { OptsService } from '../../services/opts.service';
import { SuggestionsComponent } from '../suggestions/suggestions.component';

@Component({
  selector: 'app-input-bar',
  standalone: false,
  template: `
    <div class="input-area">
      <div class="input-shell">
        <div class="terminal-bar">
          <span>AGENT TERMINAL · RWA-01</span>
          <span>{{ busy ? 'PROCESSING...' : 'READY' }}</span>
        </div>
        <app-suggestions #sug (selected)="onSuggestion($event)"></app-suggestions>
        <div class="input-main">
          <span class="term-indicator">&gt;_</span>
          <textarea
            [(ngModel)]="text"
            placeholder="Ask about assets, compliance, blockchain..."
            [disabled]="busy"
            (keydown.enter)="onEnter($event)"
            (keydown.arrowup)="onArrowUp($event)"
            rows="1"
            (input)="autoResize($event)"
          ></textarea>
          <button class="btn-send" [disabled]="busy || !text.trim()" (click)="send()">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <line x1="22" y1="2" x2="11" y2="13"/>
              <polygon points="22 2 15 22 11 13 2 9 22 2"/>
            </svg>
          </button>
        </div>
        <div class="input-footer">
          <label class="stream-toggle">
            <input type="checkbox" [checked]="opts.stream" (change)="toggleStream($event)" />
            Stream
          </label>
          <div style="display:flex;align-items:center;gap:10px">
            <button class="opts-toggle" [class.active]="optsPanelOpen" (click)="toggleOpts()" title="Options">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="12" cy="12" r="3"/>
                <path d="M19.07 4.93a10 10 0 0 1 0 14.14M4.93 4.93a10 10 0 0 0 0 14.14"/>
              </svg>
            </button>
            <button class="opts-toggle" (click)="sug.toggle()" title="Suggestions">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <line x1="8" y1="6" x2="21" y2="6"/>
                <line x1="8" y1="12" x2="21" y2="12"/>
                <line x1="8" y1="18" x2="21" y2="18"/>
                <line x1="3" y1="6" x2="3.01" y2="6"/>
                <line x1="3" y1="12" x2="3.01" y2="12"/>
                <line x1="3" y1="18" x2="3.01" y2="18"/>
              </svg>
            </button>
          </div>
        </div>
        <app-options-panel [open]="optsPanelOpen"></app-options-panel>
      </div>
    </div>
  `
})
export class InputBarComponent implements OnInit {
  @ViewChild('sug') sugRef!: SuggestionsComponent;
  text = '';
  busy = false;
  opts: any = {};
  optsPanelOpen = false;

  constructor(private chat: ChatService, private optsService: OptsService) {}

  ngOnInit() {
    this.chat.busy$.subscribe(b => this.busy = b);
    this.optsService.opts$.subscribe(o => this.opts = o);
  }

  send() {
    if (!this.text.trim() || this.busy) return;
    this.chat.send(this.text.trim(), this.optsService.snapshot);
    this.text = '';
  }

  onEnter(event: Event) {
    const ke = event as KeyboardEvent;
    if (ke.shiftKey) return;
    event.preventDefault();
    this.send();
  }

  onSuggestion(s: string) { this.text = s; }

  onArrowUp(event: Event) {
    if (!this.text && !this.busy) {
      event.preventDefault();
      this.sugRef.toggle();
    }
  }

  toggleStream(event: Event) {
    this.optsService.update({ stream: (event.target as HTMLInputElement).checked });
  }

  toggleOpts() { this.optsPanelOpen = !this.optsPanelOpen; }

  autoResize(event: Event) {
    const el = event.target as HTMLTextAreaElement;
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 140) + 'px';
  }
}

// frontend/src/components/layout/InputBar/index.jsx
import { useState, useRef } from 'react';
import Suggestions from './Suggestions.jsx';
import { OptionsPanel } from '../../../features/settings/index.js';

export default function InputBar({ onSend, busy }) {
  const [text, setText]         = useState('');
  const [sugOpen, setSugOpen]   = useState(false);
  const [optsOpen, setOptsOpen] = useState(false);
  const [stream, setStream]     = useState(true);
  const textareaRef             = useRef(null);

  function resize() {
    const ta = textareaRef.current;
    if (!ta) return;
    ta.style.height = 'auto';
    ta.style.height = Math.min(ta.scrollHeight, 140) + 'px';
  }

  function handleChange(e) {
    setText(e.target.value);
    resize();
    setSugOpen(true);
  }

  function handleFocus() { setSugOpen(true); }
  function handleBlur()  { setTimeout(() => setSugOpen(false), 150); }

  function handleKey(e) {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submit(); }
    if (e.key === 'Escape') setSugOpen(false);
  }

  function submit() {
    const msg = text.trim();
    if (!msg || busy) return;
    onSend(msg, stream);
    setText('');
    setSugOpen(false);
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
    }
  }

  function pickSuggestion(s) {
    setText(s);
    setSugOpen(false);
    textareaRef.current?.focus();
    setTimeout(resize, 0);
  }

  return (
    <div className="input-area">
      <div className="input-shell">

        {/* Suggestions */}
        {sugOpen && (
          <Suggestions query={text} onPick={pickSuggestion} />
        )}

        {/* Terminal bar */}
        <div className="terminal-bar">
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span className="status-dot" />
            <span>ONLINE</span>
          </div>
          <span>RAG_CONSOLE // LLAMA-3.3-70B</span>
        </div>

        {/* Input row */}
        <div className="input-main">
          <div className="term-indicator">HET-X &gt;</div>
          <textarea
            ref={textareaRef}
            rows={1}
            value={text}
            placeholder="Enter query or command..."
            onChange={handleChange}
            onFocus={handleFocus}
            onBlur={handleBlur}
            onKeyDown={handleKey}
          />
          <button className="btn-send" onClick={submit} disabled={busy || !text.trim()}>
            <svg viewBox="0 0 24 24">
              <line x1="12" y1="19" x2="12" y2="5" />
              <polyline points="5 12 12 5 19 12" />
            </svg>
          </button>
        </div>

        {/* Options panel */}
        <OptionsPanel open={optsOpen} />

        {/* Footer */}
        <div className="input-footer">
          <label className="stream-toggle">
            <input
              type="checkbox"
              checked={stream}
              onChange={e => setStream(e.target.checked)}
            />
            <span>STREAM</span>
          </label>
          <button
            className={`opts-toggle${optsOpen ? ' active' : ''}`}
            onClick={() => setOptsOpen(o => !o)}
            title="Options"
          >
            <svg viewBox="0 0 16 16">
              <line x1="2" y1="4"  x2="14" y2="4"  />
              <line x1="2" y1="8"  x2="14" y2="8"  />
              <line x1="2" y1="12" x2="14" y2="12" />
              <circle cx="5"  cy="4"  r="1.5" fill="currentColor" stroke="none" />
              <circle cx="10" cy="8"  r="1.5" fill="currentColor" stroke="none" />
              <circle cx="6"  cy="12" r="1.5" fill="currentColor" stroke="none" />
            </svg>
          </button>
        </div>

      </div>
    </div>
  );
}
